smiles-columns = [amine_smiles, acid_smiles]
accelerator = gpu
devices = 0,1,2,3
data-path = data/rates/nmr_lnk_smiles_splits_70_15_15.csv
output-dir = runs/chemeleon_nmr_finetune_70_15_15
checkpoint = [runs/chemeleon_lnk_bigffn_ens5_fixedsplits_ddp23_warm/model_0/best.pt]
freeze-encoder = true
dropout = 0.2
ffn-hidden-dim = 1024
ffn-num-layers = 3
batch-norm = true
target-columns = [NMR_lnk]
splits-column = split
warmup-epochs = 5
max-lr = 0.0005
epochs = 150
patience = 20
split = RANDOM
split-sizes = [0.7, 0.15, 0.15]
save-smiles-splits = true
data-seed = 0
num-workers = 0
batch-size = 64
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 300
depth = 3
aggregation = norm
aggregation-norm = 100
activation = RELU
multiclass-num-classes = 3
atom-ffn-hidden-dim = 300
atom-ffn-num-layers = 1
atom-multiclass-num-classes = 3
bond-ffn-hidden-dim = 300
bond-ffn-num-layers = 1
bond-multiclass-num-classes = 3
atom-constrainer-ffn-hidden-dim = 300
atom-constrainer-ffn-num-layers = 1
bond-constrainer-ffn-hidden-dim = 300
bond-constrainer-ffn-num-layers = 1
task-type = regression
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
init-lr = 0.0001
final-lr = 0.0001
split-key-molecule = 0
num-replicates = 1
